name : reflect-git-page
run-name: ${{ github.actor}}가 깃허브 페이지를 수정했습니다.
on: [push]
jobs : 
  upload-statics:
    runs-on : ubutun-22.04
    steps:
      - uses : actions/checkout@v3
      - uses : actions/setup-node@v3
        with:
          node-version : 18
      - run : npm install
      - run : npm run deploy